### ISSUE TITLE
Missing reward.reward_webvid file

### ISSUE THREAD

**Issue by Benjamin-So** [ali-vilab/VGen#126]
Hello, I followed the steps outlined in "InstructVideo (CVPR 2024)." I'm trying to run the evaluation step: bash configs/instructvideo/eval_generate_videos.sh but I encounter the error below. I checked the provided files in the ModelScope page but could not find the missing file. Any idea what may lead to this error?

Traceback (most recent call last):
  File "/home/policy/Desktop/Dev/VGen/utils/registry.py", line 67, in build_from_config
    return req_type_entry(**cfg)
  File "/home/policy/Desktop/Dev/VGen/tools/inferences/inference_instructvideo_entrance.py", line 81, in inference_instructvideo_entrance
    worker(0, cfg)
  File "/home/policy/Desktop/Dev/VGen/tools/inferences/inference_instructvideo_entrance.py", line 157, in worker
    load_dict = torch.load(cfg.infer_checkpoint, map_location='cpu')
  File "/home/policy/miniconda3/envs/vgen/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/policy/miniconda3/envs/vgen/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/policy/miniconda3/envs/vgen/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models/instructvideo-finetuned/reward.reward_webvid_ani45_20_reg_vidldm_LoRA_TSNExp16Diffreward_Partial06_Trunc1_Check_ddim20_1102-18-52_non_ema_0620000.pth'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inference.py", line 18, in <module>
    INFER_ENGINE.build(dict(type=cfg_update.TASK_TYPE), cfg_update=cfg_update.cfg_dict)
  File "/home/policy/Desktop/Dev/VGen/utils/registry.py", line 107, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/policy/Desktop/Dev/VGen/utils/registry_class.py", line 7, in build_func
    return build_from_config(cfg, registry, **kwargs)
  File "/home/policy/Desktop/Dev/VGen/utils/registry.py", line 69, in build_from_config
    raise Exception(f"Failed to invoke function {req_type_entry}, with {e}")
Exception: Failed to invoke function <function inference_instructvideo_entrance at 0x7f065fad4dc0>, with [Errno 2] No such file or directory: 'models/instructvideo-finetuned/reward.reward_webvid_ani45_20_reg_vidldm_LoRA_TSNExp16Diffreward_Partial06_Trunc1_Check_ddim20_1102-18-52_non_ema_0620000.pth'

**Comment by JacobYuan7** [comment]
@Benjamin-So 
Sorry about this. It seems that someone changed the name of my model, leading to this error. You can change it to `models/instructvideo-finetuned/ddim20_1102-18-52_non_ema_0620000.pth`, which could solve this.

I've opened new pull requests for this. Many thanks for your feedback.
