### ISSUE TITLE
Getting it installed and running on Windows 10..

### ISSUE THREAD

**Issue by gituser123456789000** [ali-vilab/VGen#130]
I've tried before and had tons of errors.. gave myself a break and trying again.

I downloaded the Zip file and extracted it.. downloaded anaconda.. I have my "Edit the system environment variables" > "Edit variables" > "Path" set to Python 3.8 on top.. scripts and the main folder

I follow the setup steps.. 1, 2, and 3.. I run step 4 and requirements.tst does not exist.. so where is requirements.txt? That's in the zip folder of code from the github here, so I paste all of those files over to the anaconda environment..

I cd (change directory) to the conda environment.. where the requirements.txt file now is..

Then I run step 4 again and some code runs through, but first error is:

"(vgen) PS C:\Users\USERNAME\anaconda3\envs\vgen> pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting easydict==1.10 (from -r requirements.txt (line 1))
  Using cached easydict-1.10-py3-none-any.whl
Collecting tokenizers==0.12.1 (from -r requirements.txt (line 2))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/e4/07/4220b22988667259b793cfb87cdd1fa6ef0e375d149d30ac0190ba6ced7d/tokenizers-0.12.1-cp38-cp38-win_amd64.whl (3.3 MB)
Requirement already satisfied: numpy>=1.19.2 in c:\users\username\anaconda3\envs\vgen\lib\site-packages (from -r requirements.txt (line 3)) (1.24.4)
Collecting ftfy==6.1.1 (from -r requirements.txt (line 4))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/e1/1e/bf736f9576a8979752b826b75cbd83663ff86634ea3055a766e2d8ad3ee5/ftfy-6.1.1-py3-none-any.whl (53 kB)
Collecting transformers==4.18.0 (from -r requirements.txt (line 5))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/8f/e9/c2b4c823b3959d475a570c1bd2df4125478e2e37b96fb967a87933ae7134/transformers-4.18.0-py3-none-any.whl (4.0 MB)
Collecting imageio==2.15.0 (from -r requirements.txt (line 6))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/49/f9/4986d7ea281875be92f7780b1d77c1e2e1d1b8f6669c9bb784065c7777cc/imageio-2.15.0-py3-none-any.whl (3.3 MB)
Collecting fairscale==0.4.6 (from -r requirements.txt (line 7))
  Using cached fairscale-0.4.6-py3-none-any.whl
Collecting ipdb (from -r requirements.txt (line 8))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/0c/4c/b075da0092003d9a55cf2ecc1cae9384a1ca4f650d51b00fc59875fe76f6/ipdb-0.13.13-py3-none-any.whl (12 kB)
Collecting open-clip-torch==2.0.2 (from -r requirements.txt (line 9))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/3a/d8/f4bdff87f2b2e89f6e46b6537e4f43029cf46119d196308290032468a074/open_clip_torch-2.0.2-py3-none-any.whl (1.4 MB)
Collecting xformers==0.0.13 (from -r requirements.txt (line 10))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/fd/20/da92c5ee5d20cb34e35a630ecf42a6dcd22523d5cb5adb56a0ffe8d03cfa/xformers-0.0.13.tar.gz (292 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\USERNAME\AppData\Local\Temp\pip-install-7efz_oao\xformers_76defd4f1ddd4088bfb9617984846c76\setup.py", line 239, in <module>
          ext_modules=get_extensions(),
        File "C:\Users\USERNAME\AppData\Local\Temp\pip-install-7efz_oao\xformers_76defd4f1ddd4088bfb9617984846c76\setup.py", line 157, in get_extensions
          raise RuntimeError(
      RuntimeError: CUTLASS submodule not found. Did you forget to run `git submodule update --init --recursive` ?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details."

So the first failure is on xformers I assume? Help on how to get beyond this error and onto the next one?

**Comment by gituser123456789000** [comment]
I changed xformers==0.0.13 to xformers==0.0.12 in requirements and got past this error.

That may be a problem. Maybe 0.0.12 doesn't perform similarly or at all to 0.0.13 in this program.. we'll see.. but onto the next error

Next error is:

Collecting simplejson==3.18.4 (from -r requirements.txt (line 16))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/26/65/b6eae8046756a24d94c0be3b3375153ca15a7fc0708ae859d852e9e53d84/simplejson-3.18.4-cp38-cp38-win_amd64.whl (74 kB)
ERROR: Could not find a version that satisfies the requirement motion-vector-extractor==1.0.6 (from versions: none)
ERROR: No matching distribution found for motion-vector-extractor==1.0.6

so it fails on motion-vector-extractor==1.0.6

**Comment by gituser123456789000** [comment]
ok.. I'm getting far along now by following this comment:
https://github.com/ali-vilab/VGen/issues/9#issuecomment-1858809173

In requirements I changed xformers to 0.0.16

And you have to comment out motion-vector-extractor==1.0.6 and triton==2.0.0.dev20221120... comment out means you have to  put # in front of them.. so requirements.txt should look like 

easydict==1.10
tokenizers==0.12.1
numpy>=1.19.2
ftfy==6.1.1
transformers==4.18.0
imageio==2.15.0
fairscale==0.4.6
ipdb
open-clip-torch==2.0.2
xformers==0.0.16
chardet==5.1.0
torchdiffeq==0.2.3
opencv-python==4.4.0.46
opencv-python-headless==4.7.0.68
torchsde==0.2.6
simplejson==3.18.4
#motion-vector-extractor==1.0.6
scikit-learn
scikit-image
rotary-embedding-torch==0.2.1
pynvml==11.5.0
#triton==2.0.0.dev20221120
pytorch-lightning==1.4.2
torchmetrics==0.6.0
gradio==3.39.0
imageio-ffmpeg
piq

**Comment by gituser123456789000** [comment]
pip3 install tools

command fixed that error...
next error....

Someone also wrote:
"If you have multiple python installations, make sure you are installing the package for the correct python version. To install a package for python3.x use python3.x -m pip install {package}"

too late for me to follow that advice

next error is:

Traceback (most recent call last):
  File "train_net.py", line 18, in <module>
    ENGINE.build(dict(type=cfg_update.TASK_TYPE), cfg_update=cfg_update.cfg_dict)
  File "C:\Users\USERNAME\anaconda3\envs\vgen\utils\registry.py", line 107, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "C:\Users\USERNAME\anaconda3\envs\vgen\utils\registry_class.py", line 7, in build_func
    return build_from_config(cfg, registry, **kwargs)
  File "C:\Users\USERNAME\anaconda3\envs\vgen\utils\registry.py", line 55, in build_from_config
    raise KeyError(f"{req_type} not found in {registry.name} registry")
KeyError: 'train_t2v_entrance not found in ENGINE registry'

Ideas on how to fix this one?
