### ISSUE TITLE
pip install fail

### ISSUE THREAD

**Issue by Love-Glimpse** [ali-vilab/VGen#150]
when  i execute pip install -r requirements.txt
then

error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\xxx\AppData\Local\Temp\pip-install-8cnkwhgs\xformers_3133ba21d9144d4c8657ff9588dc942f\setup.py", line 239, in <module>
          ext_modules=get_extensions(),
                      ^^^^^^^^^^^^^^^^
        File "C:\Users\xxx\AppData\Local\Temp\pip-install-8cnkwhgs\xformers_3133ba21d9144d4c8657ff9588dc942f\setup.py", line 157, in get_extensions
          raise RuntimeError(
      RuntimeError: CUTLASS submodule not found. Did you forget to run `git submodule update --init --recursive` ?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by AlirezaParchami** [comment]
you need to install xformers.
after installing CUDA and related pyTorch version (that matches with the CUDA version), xformers can be installed by:

```
git clone https://github.com/facebookresearch/xformers.git
cd xformers
git submodule update --init --recursive
pip install .
```

However, there might be some challenges and dependencies during the installation that needs to be mitigated. That took some time from me, but finally worked!
